# Site settings
title: "Neil Ghosh"
email: neil.ghosh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Knowledge has no value until it is practiced !
baseurl: ""
url: "https://www.neilghosh.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: neilghosh
github_username:  neilghosh

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed
  
# Theme
remote_theme: jekyll/minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap

# Author info for SEO
author:
  name: "Neil Ghosh"
  email: "neil.ghosh@gmail.com"
  twitter: "neilghosh"

# Permalinks
permalink: /:year/:month/:title.html
paginate: 5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Google Analytics
google_analytics: G-86MKLSMHW6
